// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJS1_tTwk-jXDVfhib5A7_OrviazxsuhA',
    appId: '1:395957134531:web:fa56fc50f9acf207d32e76',
    messagingSenderId: '395957134531',
    projectId: 'cityguideapp-b4410',
    authDomain: 'cityguideapp-b4410.firebaseapp.com',
    storageBucket: 'cityguideapp-b4410.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqI57szliZrf592xcdSPcYR9nCks1Fxk',
    appId: '1:395957134531:android:409c0a8cfb95b5b8d32e76',
    messagingSenderId: '395957134531',
    projectId: 'cityguideapp-b4410',
    storageBucket: 'cityguideapp-b4410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNbQUH8zqm8koZAI4jxS2KuYURld9Upvo',
    appId: '1:395957134531:ios:479b285b9855e73ed32e76',
    messagingSenderId: '395957134531',
    projectId: 'cityguideapp-b4410',
    storageBucket: 'cityguideapp-b4410.appspot.com',
    androidClientId: '395957134531-rabj0lgjgeomhsiqh6776o24hc4dkgtb.apps.googleusercontent.com',
    iosClientId: '395957134531-mh07mcioh4vvs6h7gmfivgl81k5otlsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cityGuideApp',
  );
}
